### ISSUE TITLE
Have the option to retain the install-config.yaml file used for installing an openshift cluster

### ISSUE THREAD

**Issue by danalanerh** [oasis-roles/ocp_install#2]
Currently, openshift-install consumes (deleted) the install-config.yaml file once the install starts. I'd like to have an option to retain this file as a backup for future use. It can be named different to avoid confusion, like install-config.bak or something along those lines.

**Comment by robled** [comment]
I agree that the behavior of the OpenShift installer where it deletes the generated `install-config.yaml` can make development more difficult.  It sure would be nice to see the contents of that file for review.  It seems to do this by design, but I don't know why.

It's debatable whether this should be worked-around in an OASIS Ansible role or filed as a bug/enhancement for OpenShift, but if we were to create a work-around, the implementation might look something like this:

**tasks/main.yml:**
```
- name: create openshift install config
  template:
    src: "{{ coreos_infra_template_openshift }}"
    dest: "{{ coreos_infra_oc_configs }}/install-config.yaml"
    owner: "{{ coreos_infra_oc_user }}"
    group: "{{ coreos_infra_oc_user }}"
    mode: 0600
  become: "{{ coreos_infra_become }}"
  become_user: "{{ coreos_infra_oc_user }}"
  notify: run openshift installer

- name: run installer now
  meta: flush_handlers

# we run this again because the openshift installer deletes it, and we want to
# be idempotent
- name: re-create openshift install config
  template:
    src: "{{ coreos_infra_template_openshift }}"
    dest: "{{ coreos_infra_oc_configs }}/install-config.yaml"
    owner: "{{ coreos_infra_oc_user }}"
    group: "{{ coreos_infra_oc_user }}"
    mode: 0600
  become: "{{ coreos_infra_become }}"
  become_user: "{{ coreos_infra_oc_user }}"
```

**handlers/main.yml:**
```
- name: run openshift installer
  command: "{{ coreos_infra_oc_install_path }}/openshift-install --dir={{ coreos_infra_oc_configs }} create ignition-configs"
  become: "{{ coreos_infra_become }}"
  become_user: "{{ coreos_infra_oc_user }}"
```

**Comment by tehsmyers** [comment]
In thinking about it, I'm skeptical as to the usefulness of saving the install config file. The install-config generated by this role is, well, generated by this role. Therefore, in order to "retain this file as a backup for future use", run the role again using the same input vars. If you're after repeatability, *retain those input vars* for future use.

That said, the role does not prevent you from using it however you might like. Employing droble's suggestions while using existing role functionality could mean using `include_role` explicitly in a play  rather than listing `ocp_install` in its `roles` stanza:

```yaml
- <insert play stuff here>
  tasks:
    - name: Create install config
      include_role:
        name: oasis_roles.ocp_install
        vars:
          ocp_install_generate_config: true
          ocp_install_create_cluster: false
    - name: Do whatever you want
       thingdoer: do a thing
    - name: Create ocp cluster
      include_role:
        name: oasis_roles.ocp_install
        vars:
          # config generation tasks will run again, but report 'ok' instead of 'changed' due to
          # idempotence, unless tasks ran after config generation to break idempotence
          ocp_install_create_cluster: true
```
