### ISSUE TITLE
Add support to fail the role when the openshift install does not finish properly

### ISSUE THREAD

**Issue by ryankwilliams** [oasis-roles/ocp_install#7]
It would be great to see this role raise a failure if the OpenShift install either fails mid-way or exceeds the total time checking the openshift-installer command called. This would provide the ability for playbooks using this role, to handle how they want to continue. Right now if multiple tasks are called after this role, they will continue on since nothing was notified as a failure (if a failure happened).

Maybe its possible to add another task within the `rescue` [1] clause, to use the `fail` module to alert that the install did not properly complete.

```yaml
- block:
    - name: Run openshift-install create cluster
      command: >-
        {{ ocp_install_path }}/openshift-install create cluster
        --dir "{{ ocp_install_config_dir }}"
        --log-level "{{ ocp_install_log_level }}"
      async: "{{ ocp_install_async_timeout }}"
      poll: 0
      when: ocp_install_create_cluster
      register: ocp_install_create_cluster_async

    - name: Poll openshift-install create cluster task status
      async_status:
        jid: "{{ ocp_install_create_cluster_async.ansible_job_id }}"
      register: ocp_install_create_cluster_result
      until: ocp_install_create_cluster_result is finished
      delay: "{{ ocp_install_async_poll }}"
      retries: "{{ ocp_install_async_retries }}"
  rescue:
    - name: Run openshift-install destroy cluster
      include_tasks: destroy_cluster.yml
      when: ocp_install_destroy_cluster_on_failure

    - name: OpenShift install failed
      fail:
        msg: "OpenShift install failed to successfully finish."
      when: ocp_install_create_cluster_result.failed
```

This then could stop a playbook from processing any other tasks or provide the ability for them to wrap the role in a `block|rescue`. Giving control to do any last minute tasks to help troubleshoot the install (e.g. collect openshift install log files).

```yaml
    - block:
        - name: Install OpenShift cluster
          import_role:
            name: oasis_roles.ocp_install
          vars:
            ocp_install_generate_config: false
            ocp_install_create_cluster: true
            ocp_install_async_timeout: 5400
            ocp_install_async_poll: 30
      rescue:
        - name: Fail due to OpenShift deployment failed to complete
          fail:
            msg: "OpenShift cluster deployment failed."
      always:
        - name: Archive OpenShift install directory
          archive:
            path: "{{ ocp_install_config_dir }}"
            dest: /tmp/ocp-install.tar.gz
            format: gz

        - name: Fetch OpenShift install archive
          fetch:
            src: /tmp/ocp-install.tar.gz
            dest: ./
            flat: true
```

[1] https://github.com/oasis-roles/ocp_install/blob/master/tasks/create_cluster.yml
